-- SundayQuiz — QUIZ MODE (the namesake): a Kahoot-style live Q&A game_type.
-- NET-NEW in-mode logic that reuses the generic shell (games/players/lifecycle,
-- PIN join, resume, presence) untouched. Shares NOTHING with bingo's marking
-- logic (spec §2). Atomic server-side scoring mirrors the mark RPC pattern from
-- 0002 (a TS twin lives in lib/quiz-scoring.ts — keep in lockstep).
--
-- Idempotent + additive: re-runnable. Drops/recreates the game_type CHECK to
-- add 'quiz', creates new tables only if absent, seeds only when empty.

-- ---------- 1. widen the game_type CHECK to admit 'quiz' ----------
-- Constraint name is generated by Postgres for an inline `check (...)`; find
-- and drop whichever CHECK governs game_type, then re-add the widened one. This
-- is safe to re-run (the new constraint is dropped first if present).
do $$
declare
  c record;
begin
  for c in
    select con.conname
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace ns on ns.oid = rel.relnamespace
    where ns.nspname = 'quiz'
      and rel.relname = 'games'
      and con.contype = 'c'
      and pg_get_constraintdef(con.oid) ilike '%game_type%'
  loop
    execute format('alter table quiz.games drop constraint %I', c.conname);
  end loop;
  alter table quiz.games
    add constraint games_game_type_check
    check (game_type in ('bingo', 'quiz'));
end $$;

-- ---------- 2. question sets (parallel to statement_sets) ----------
create table if not exists quiz.question_sets (
  id            uuid primary key default gen_random_uuid(),
  owner_user_id uuid,                                              -- reserved for suite auth (v2)
  game_id       uuid references quiz.games (id) on delete cascade, -- custom set: lives with its game
  title         text not null check (length(title) between 1 and 80),
  audience      text not null default 'generell' check (audience in ('kirke','skole','generell')),
  is_builtin    boolean not null default false,
  language      text not null default 'nb',
  created_at    timestamptz not null default now()
);
create index if not exists question_sets_game_idx
  on quiz.question_sets (game_id) where game_id is not null;

create table if not exists quiz.questions (
  id            uuid primary key default gen_random_uuid(),
  set_id        uuid not null references quiz.question_sets (id) on delete cascade,
  prompt        text not null check (length(prompt) between 1 and 300),
  -- exactly 4 answer options, index 0..3 → coloured tile on the board.
  options       jsonb not null,
  correct_index int not null check (correct_index between 0 and 3),
  sort_order    int not null default 0,
  -- 4 options exactly; jsonb_array_length guards a malformed seed/custom set.
  constraint questions_four_options check (jsonb_array_length(options) = 4)
);
create index if not exists questions_set_idx on quiz.questions (set_id);

-- ---------- 3. live quiz state (one row per quiz game) ----------
-- The host advances a single shared question stream; this row is the
-- authoritative cursor + phase + question-open timestamp (drives speed scoring
-- and the board countdown). Created lazily on first advance.
create table if not exists quiz.quiz_state (
  id                  uuid primary key default gen_random_uuid(),
  game_id             uuid not null unique references quiz.games (id) on delete cascade,
  current_index       int not null default -1,                       -- -1 before the first question
  phase               text not null default 'idle'
                        check (phase in ('idle','question','reveal','ended')),
  question_started_at timestamptz
);

-- ---------- 4. answers (one per player per question; audit + score source) ----------
create table if not exists quiz.answers (
  id          uuid primary key default gen_random_uuid(),
  game_id     uuid not null references quiz.games (id) on delete cascade,
  question_id uuid not null references quiz.questions (id) on delete cascade,
  player_id   uuid not null references quiz.players (id) on delete cascade,
  choice      int not null check (choice between 0 and 3),
  correct     boolean not null,
  points      int not null default 0,
  answered_at timestamptz not null default now(),
  -- one answer per player per question (lock-in; no changing your mind).
  unique (game_id, question_id, player_id)
);
create index if not exists answers_game_idx on quiz.answers (game_id);
create index if not exists answers_question_idx on quiz.answers (game_id, question_id);

-- ---------- 5. RLS: lock new tables to the service role (same as 0001) ----------
alter table quiz.question_sets enable row level security;
alter table quiz.questions     enable row level security;
alter table quiz.quiz_state    enable row level security;
alter table quiz.answers       enable row level security;
-- No policies on purpose → anon/authenticated get zero direct access.
grant all on quiz.question_sets to service_role;
grant all on quiz.questions     to service_role;
grant all on quiz.quiz_state    to service_role;
grant all on quiz.answers       to service_role;

-- ---------- 6. pure scoring (TS twin: lib/quiz-scoring.ts) ----------
-- Wrong = 0. 'flat' correct = 1000. 'speed' correct decays linearly from 1000
-- (instant) to 100 (buzzer); elapsed clamped to [0, window]; window <= 0 → 100.
create or replace function quiz.score_answer(
  p_correct boolean,
  p_points_mode text,
  p_elapsed_ms double precision,
  p_window_ms double precision
) returns int
language plpgsql
immutable
as $$
declare
  v_max   int := 1000;
  v_min   int := 100;
  v_clamp double precision;
  v_frac  double precision;
begin
  if not p_correct then return 0; end if;
  if p_points_mode = 'flat' then return v_max; end if;
  if p_window_ms <= 0 then return v_min; end if;
  v_clamp := greatest(0, least(p_elapsed_ms, p_window_ms));
  v_frac  := v_clamp / p_window_ms;
  return round(v_max - v_frac * (v_max - v_min))::int;
end;
$$;

-- ---------- 7. advance_question (host action: open next / reveal / end) ----------
-- Lifecycle of the shared stream, all server-authoritative:
--   action 'next'   : idle/reveal → open the next question ('question' phase),
--                      stamp question_started_at, advance the index. If there
--                      is no next question it ends the quiz (game → finished).
--   action 'reveal' : question → 'reveal' (close answering, show leaderboard).
--   action 'end'    : → ended + game finished (the host stops early).
-- Returns the resulting quiz_state row plus the total question count so the
-- caller knows whether the quiz finished.
create or replace function quiz.advance_question(
  p_game_id uuid,
  p_action text
) returns jsonb
language plpgsql
as $$
declare
  v_game  quiz.games%rowtype;
  v_state quiz.quiz_state%rowtype;
  v_total int;
  v_next  int;
begin
  select * into v_game from quiz.games where id = p_game_id for update;
  if not found then raise exception 'game_not_found'; end if;
  if v_game.game_type <> 'quiz' then raise exception 'not_quiz'; end if;
  if v_game.status = 'finished' then raise exception 'game_not_live'; end if;

  -- Upsert + lock the state row (lazy create on first advance).
  insert into quiz.quiz_state (game_id) values (p_game_id)
    on conflict (game_id) do nothing;
  select * into v_state from quiz.quiz_state
    where game_id = p_game_id for update;

  select count(*) into v_total from quiz.questions
    where set_id = (v_game.config ->> 'questionSetId')::uuid;

  if p_action = 'end' then
    update quiz.quiz_state set phase = 'ended' where game_id = p_game_id
      returning * into v_state;
    update quiz.games set status = 'finished', ended_at = now()
      where id = p_game_id and status <> 'finished';

  elsif p_action = 'reveal' then
    if v_state.phase <> 'question' then raise exception 'not_in_question'; end if;
    update quiz.quiz_state set phase = 'reveal' where game_id = p_game_id
      returning * into v_state;

  elsif p_action = 'next' then
    if v_state.phase = 'question' then raise exception 'question_open'; end if;
    v_next := v_state.current_index + 1;
    if v_next >= v_total then
      -- no more questions → finish the quiz
      update quiz.quiz_state set phase = 'ended' where game_id = p_game_id
        returning * into v_state;
      update quiz.games set status = 'finished', ended_at = now()
        where id = p_game_id and status <> 'finished';
    else
      -- flip the game live on the first question (lobby → live).
      update quiz.games set status = 'live',
             started_at = coalesce(started_at, now())
        where id = p_game_id and status = 'lobby';
      update quiz.quiz_state
        set current_index = v_next,
            phase = 'question',
            question_started_at = now()
        where game_id = p_game_id
        returning * into v_state;
    end if;

  else
    raise exception 'invalid_action';
  end if;

  return jsonb_build_object('state', to_jsonb(v_state), 'totalQuestions', v_total);
end;
$$;

-- ---------- 8. submit_answer (player action: tap one of 4) ----------
-- Atomic: validates the question is the one currently open, computes points
-- server-side (the elapsed time is measured against question_started_at, NEVER
-- trusted from the client), locks in exactly one answer per player+question.
-- Mirrors create_mark's "all validation inside the RPC" discipline.
create or replace function quiz.submit_answer(
  p_game_id uuid,
  p_player_id uuid,
  p_question_id uuid,
  p_choice int
) returns jsonb
language plpgsql
as $$
declare
  v_game     quiz.games%rowtype;
  v_state    quiz.quiz_state%rowtype;
  v_question quiz.questions%rowtype;
  v_set_id   uuid;
  v_correct  boolean;
  v_elapsed  double precision;
  v_window   double precision;
  v_points   int;
  v_answer   quiz.answers%rowtype;
begin
  if p_choice < 0 or p_choice > 3 then raise exception 'invalid_choice'; end if;

  select * into v_game from quiz.games where id = p_game_id;
  if not found then raise exception 'game_not_found'; end if;
  if v_game.game_type <> 'quiz' then raise exception 'not_quiz'; end if;
  if v_game.status <> 'live' then raise exception 'game_not_live'; end if;

  perform 1 from quiz.players
    where id = p_player_id and game_id = p_game_id and status = 'active';
  if not found then raise exception 'invalid_player'; end if;

  select * into v_state from quiz.quiz_state where game_id = p_game_id for update;
  if not found or v_state.phase <> 'question' then
    raise exception 'no_open_question';
  end if;

  v_set_id := (v_game.config ->> 'questionSetId')::uuid;
  -- The question being answered must be the one currently open (by index into
  -- the ordered list). Block answering a past/future question (replayed POST).
  select q.* into v_question
    from quiz.questions q
    where q.set_id = v_set_id
    order by q.sort_order, q.id
    offset v_state.current_index limit 1;
  if not found or v_question.id <> p_question_id then
    raise exception 'wrong_question';
  end if;

  v_correct := (p_choice = v_question.correct_index);
  v_window  := coalesce((v_game.config ->> 'perQuestionSeconds')::double precision, 20) * 1000;
  v_elapsed := extract(epoch from (now() - coalesce(v_state.question_started_at, now()))) * 1000;
  v_points  := quiz.score_answer(
    v_correct,
    coalesce(v_game.config ->> 'pointsMode', 'speed'),
    v_elapsed,
    v_window
  );

  begin
    insert into quiz.answers
      (game_id, question_id, player_id, choice, correct, points)
    values
      (p_game_id, p_question_id, p_player_id, p_choice, v_correct, v_points)
    returning * into v_answer;
  exception when unique_violation then
    raise exception 'already_answered';
  end;

  return to_jsonb(v_answer);
end;
$$;

grant execute on all functions in schema quiz to service_role;

-- ---------- 9. seed: one small Norwegian sample question set (Bibel/preken) ----------
-- Fixed id so re-runs are idempotent; questions inserted only when empty. Tone
-- matches the bundled statement sets: warm, low-threshold, nothing as a
-- gotcha. Audience 'kirke' (sermon-recap / Bibelkunnskap).
insert into quiz.question_sets (id, title, audience, is_builtin, language) values
  ('b2000000-0000-4000-8000-000000000001', 'Bibelquiz — bli kjent med fortellingene', 'kirke', true, 'nb')
on conflict (id) do nothing;

insert into quiz.questions (set_id, prompt, options, correct_index, sort_order)
select 'b2000000-0000-4000-8000-000000000001', q.prompt, q.options::jsonb, q.correct_index, q.ord
from (
  values
    ('Hvor mange dager varte skapelsen før hviledagen?',
     '["Tre","Seks","Sju","Tolv"]', 1, 1),
    ('Hvem bygde arken?',
     '["Moses","Abraham","Noah","David"]', 2, 2),
    ('I hvilken by ble Jesus født?',
     '["Nasaret","Jerusalem","Betlehem","Kapernaum"]', 2, 3),
    ('Hvor mange disipler valgte Jesus ut?',
     '["Sju","Ti","Tolv","Sytti"]', 2, 4),
    ('Hva het havet Jesus stilnet stormen på?',
     '["Middelhavet","Genesaretsjøen","Dødehavet","Rødehavet"]', 1, 5),
    ('Hvem forrådte Jesus med et kyss?',
     '["Peter","Judas","Tomas","Johannes"]', 1, 6),
    ('Hva slags fortelling er den om den barmhjertige samaritan?',
     '["En salme","En lignelse","Et brev","En profeti"]', 1, 7),
    ('Hvilken bok er den første i Bibelen?',
     '["Matteus","Salmenes bok","Første Mosebok","Johannes"]', 2, 8),
    ('Hvor mange brød mettet Jesus folkemengden med (i tillegg til fisk)?',
     '["To","Fem","Tolv","Sju"]', 1, 9),
    ('Hva ba Jesus disiplene om å gjøre med hverandre, ifølge det nye bud?',
     '["Konkurrere","Elske hverandre","Tie stille","Reise hver for seg"]', 1, 10)
) as q(prompt, options, correct_index, ord)
where not exists (
  select 1 from quiz.questions where set_id = 'b2000000-0000-4000-8000-000000000001'
);
